name: Build and Deploy Maintenance WebAPI

# Trigger workflow on push to master branch
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Maintenance.WebAPI/Maintenance.WebAPI.csproj

      # Build project
      - name: Build project
        run: dotnet build Maintenance.WebAPI/Maintenance.WebAPI.csproj --configuration Release --no-restore

      # Publish project
      - name: Publish project
        run: dotnet publish Maintenance.WebAPI/Maintenance.WebAPI.csproj --configuration Release --output ./publish

      # Deploy to Azure Web App
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: maintenance-webapi-nirali
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

          # -------- PUBLISH MVC --------
      - name: Publish MVC
        run: dotnet publish 8927978_Nirali_CarRentalApplication/8927978_Nirali_CarRentalApplication.csproj -c Release -o publish-mvc

    # -------- DEPLOY MVC --------
      - name: Deploy MVC to Azure
        uses: azure/webapps-deploy@v3
        with:
           app-name: 'nirali-carrental-mvc'
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_MVC }}
           package: publish-mvc


